### ISSUE TITLE
When I run run_easiergui.bat I get an error

### ISSUE THREAD

**Issue by AlexRO110** [kalomaze/QuickMangioFixes#3]
Traceback (most recent call last):
  File "C:\Users\Alex\Desktop\RVC_V2_Mangio-crepe_fork\EasierGUI.py", line 1457, in <module>
    if(config.is_cli):
AttributeError: 'Config' object has no attribute 'is_cli'

**Comment by teufortressIndustries** [comment]
same here, i tried deleting the code from the EasierGUI.py to avoid the config checks, it eventually launched but won't convert anything.

C:\AIstuff\Mangio-RVC-Fork>C:\AIstuff\Mangio-RVC-Fork\runtime\python.exe EasierGUI.py --pycmd C:\AIstuff\Mangio-RVC-Fork\runtime\python.exe --port 7897
loading weights/Engineer.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Running on local URL:  http://0.0.0.0:7897
loading weights/Spy.pth
gin_channels: 256 self.spk_embed_dim: 109
<All keys matched successfully>
Traceback (most recent call last):
  File "C:\AIstuff\Mangio-RVC-Fork\EasierGUI.py", line 173, in vc_single
    audio_opt = vc.pipeline(
TypeError: pipeline() got multiple values for argument 'f0_file'

Traceback (most recent call last):
  File "C:\AIstuff\Mangio-RVC-Fork\runtime\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AIstuff\Mangio-RVC-Fork\runtime\lib\site-packages\gradio\blocks.py", line 1349, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\AIstuff\Mangio-RVC-Fork\runtime\lib\site-packages\gradio\blocks.py", line 1283, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\AIstuff\Mangio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 2586, in postprocess
    file_path = self.audio_to_temp_file(
  File "C:\AIstuff\Mangio-RVC-Fork\runtime\lib\site-packages\gradio\components.py", line 360, in audio_to_temp_file
    temp_dir = Path(dir) / self.hash_bytes(data.tobytes())
AttributeError: 'NoneType' object has no attribute 'tobytes'
